"""initial_schema

Revision ID: 36c402e69a90
Revises: 
Create Date: 2026-07-22 15:12:21.618485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36c402e69a90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('emergency_contact', sa.Text(), nullable=True),
    sa.Column('preferred_reminder', sa.String(length=16), nullable=True),
    sa.Column('contact_method', sa.String(length=32), nullable=True),
    sa.Column('preferred_environment', sa.String(length=64), nullable=True),
    sa.Column('care_goal', sa.Text(), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('trigger_preferences', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('trigger_sensitivities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_day_symp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('daily_night_symp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('daily_limit_activity', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('symptoms_logged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('puffs_today', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('triggers', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('calendar_event', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_check_ins_user_date')
    )
    op.create_table('env_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_env_snapshots_user_date')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('forecast_for', sa.Date(), nullable=False),
    sa.Column('flare_probability', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('advice', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wearables_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('sedentary_minutes', sa.Integer(), nullable=True),
    sa.Column('running_minutes', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_wearables_user_date')
    )
    op.create_table('inhaler_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('check_in_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('puff', 'manual_override', name='inhalereventtype'), nullable=False),
    sa.Column('puffs_delta', sa.Integer(), nullable=False),
    sa.Column('puffs_total_after', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inhaler_events')
    op.drop_table('wearables_daily')
    op.drop_table('forecasts')
    op.drop_table('env_snapshots')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute('DROP TYPE IF EXISTS inhalereventtype')
    # ### end Alembic commands ###
